# Generated by Django 5.2.7 on 2025-10-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
